# wiki build and deploy 

name: wiki-build-workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build wiki
    if: github.repository == 'bigtreetech-beta/bigtreetech-wiki-neo'
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Environment
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
        
    - name: Install dependencies
      run: yarn install
      
    - name: build wiki 
      run: yarn run build

    # to cloudflare R2
    - name: Install rclone
      run: |
        sudo apt update
        sudo apt install -y rclone

    - name: Configure rclone (Cloudflare R2 only)
      run: |
        rclone config create r2 s3 \
          provider=Cloudflare \
          access_key_id=${{ secrets.R2_ACCESS_KEY_ID }} \
          secret_access_key=${{ secrets.R2_SECRET_ACCESS_KEY }} \
          endpoint=https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com

    - name: Copy build to Cloudflare R2
      run: |
        rclone copy build r2:${{ secrets.R2_BUCKET }} \
          --fast-list \
          --checkers=32 \
          --transfers=16 \
          --progress

    # to aliyun oss 
    - name: setup aliyun oss
      uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
    - name: cp files to aliyun
      run: ossutil cp -rf ./build oss://btt-wiki/
